# Generated by Django 3.0.4 on 2020-10-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postccb',
            name='date_of_1st_declaration',
        ),
        migrations.RemoveField(
            model_name='postccb',
            name='date_of_2nd_declaration',
        ),
        migrations.RemoveField(
            model_name='postccb',
            name='date_of_3rd_declaration',
        ),
        migrations.RemoveField(
            model_name='postccb',
            name='date_of_4th_declaration',
        ),
        migrations.RemoveField(
            model_name='postccb',
            name='date_of_5th_declaration',
        ),
        migrations.RemoveField(
            model_name='postccb',
            name='date_of_6th_declaration',
        ),
        migrations.RemoveField(
            model_name='postccb',
            name='date_of_7th_declaration',
        ),
        migrations.RemoveField(
            model_name='postccb',
            name='date_of_8th_declaration',
        ),
        migrations.RemoveField(
            model_name='postccb',
            name='date_of_9th_declaration',
        ),
        migrations.AddField(
            model_name='postccb',
            name='year_of_1st_declaration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postccb',
            name='year_of_2nd_declaration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postccb',
            name='year_of_3rd_declaration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postccb',
            name='year_of_4th_declaration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postccb',
            name='year_of_5th_declaration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postccb',
            name='year_of_6th_declaration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postccb',
            name='year_of_7th_declaration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postccb',
            name='year_of_8th_declaration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postccb',
            name='year_of_9th_declaration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
