# Generated by Django 3.0.4 on 2020-10-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0002_auto_20201010_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='postccb',
            name='year_First_Decl',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
