# Generated by Django 3.0.4 on 2020-10-11 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0004_auto_20201011_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postccb',
            old_name='actual_year_of_First_Decl',
            new_name='supposed_year_to_declare',
        ),
    ]
