# Generated by Django 3.0.4 on 2020-10-11 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0005_auto_20201011_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postccb',
            name='supposed_year_to_declare',
        ),
    ]
