# Generated by Django 3.0.4 on 2020-10-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0006_remove_postccb_supposed_year_to_declare'),
    ]

    operations = [
        migrations.AddField(
            model_name='postccb',
            name='supposed_year_to_declare',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
