# Generated by Django 3.0.4 on 2020-10-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0007_postccb_supposed_year_to_declare'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postccb',
            old_name='supposed_year_to_declare',
            new_name='supposed_year_to_declare1',
        ),
        migrations.AddField(
            model_name='postccb',
            name='supposed_year_to_declare2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postccb',
            name='supposed_year_to_declare3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postccb',
            name='supposed_year_to_declare4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postccb',
            name='supposed_year_to_declare5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postccb',
            name='supposed_year_to_declare6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postccb',
            name='supposed_year_to_declare7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postccb',
            name='supposed_year_to_declare8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postccb',
            name='supposed_year_to_declare9',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
