# Generated by Django 3.0.4 on 2020-12-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0008_auto_20201011_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCBFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pics')),
            ],
        ),
    ]
