# Generated by Django 3.0.4 on 2020-12-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0009_ccbfileupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CCBFileUpload',
        ),
        migrations.RenameField(
            model_name='postefcc',
            old_name='date_of_1st_declaration',
            new_name='retiring_at_35',
        ),
        migrations.RenameField(
            model_name='postefcc',
            old_name='date_of_2nd_declaration',
            new_name='retiring_at_60',
        ),
        migrations.RenameField(
            model_name='posticpc',
            old_name='date_of_1st_declaration',
            new_name='retiring_at_35',
        ),
        migrations.RenameField(
            model_name='posticpc',
            old_name='date_of_2nd_declaration',
            new_name='retiring_at_60',
        ),
        migrations.RemoveField(
            model_name='postefcc',
            name='date_of_3rd_declaration',
        ),
        migrations.RemoveField(
            model_name='postefcc',
            name='date_of_4th_declaration',
        ),
        migrations.RemoveField(
            model_name='postefcc',
            name='date_of_5th_declaration',
        ),
        migrations.RemoveField(
            model_name='postefcc',
            name='date_of_6th_declaration',
        ),
        migrations.RemoveField(
            model_name='postefcc',
            name='date_of_7th_declaration',
        ),
        migrations.RemoveField(
            model_name='postefcc',
            name='date_of_8th_declaration',
        ),
        migrations.RemoveField(
            model_name='postefcc',
            name='date_of_9th_declaration',
        ),
        migrations.RemoveField(
            model_name='posticpc',
            name='date_of_3rd_declaration',
        ),
        migrations.RemoveField(
            model_name='posticpc',
            name='date_of_4th_declaration',
        ),
        migrations.RemoveField(
            model_name='posticpc',
            name='date_of_5th_declaration',
        ),
        migrations.RemoveField(
            model_name='posticpc',
            name='date_of_6th_declaration',
        ),
        migrations.RemoveField(
            model_name='posticpc',
            name='date_of_7th_declaration',
        ),
        migrations.RemoveField(
            model_name='posticpc',
            name='date_of_8th_declaration',
        ),
        migrations.RemoveField(
            model_name='posticpc',
            name='date_of_9th_declaration',
        ),
        migrations.AddField(
            model_name='postefcc',
            name='Num_Of_Times_To_declare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postefcc',
            name='Num_Of_Times_declared',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postefcc',
            name='Num_Of_Times_defaulted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postefcc',
            name='Year_Of_Next_declaration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postefcc',
            name='age_OR',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postefcc',
            name='age_at_fa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postefcc',
            name='curr_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postefcc',
            name='supposed_year_to_declare1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postefcc',
            name='supposed_year_to_declare2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postefcc',
            name='supposed_year_to_declare3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postefcc',
            name='supposed_year_to_declare4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postefcc',
            name='supposed_year_to_declare5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postefcc',
            name='supposed_year_to_declare6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postefcc',
            name='supposed_year_to_declare7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postefcc',
            name='supposed_year_to_declare8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postefcc',
            name='supposed_year_to_declare9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postefcc',
            name='year_FAPPT',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postefcc',
            name='year_OR',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postefcc',
            name='year_ob',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postefcc',
            name='year_of_1st_declaration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postefcc',
            name='year_of_2nd_declaration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postefcc',
            name='year_of_3rd_declaration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postefcc',
            name='year_of_4th_declaration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postefcc',
            name='year_of_5th_declaration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postefcc',
            name='year_of_6th_declaration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postefcc',
            name='year_of_7th_declaration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postefcc',
            name='year_of_8th_declaration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postefcc',
            name='year_of_9th_declaration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posticpc',
            name='Num_Of_Times_To_declare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posticpc',
            name='Num_Of_Times_declared',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posticpc',
            name='Num_Of_Times_defaulted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posticpc',
            name='Year_Of_Next_declaration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posticpc',
            name='age_OR',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posticpc',
            name='age_at_fa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posticpc',
            name='curr_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posticpc',
            name='supposed_year_to_declare1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posticpc',
            name='supposed_year_to_declare2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posticpc',
            name='supposed_year_to_declare3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posticpc',
            name='supposed_year_to_declare4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posticpc',
            name='supposed_year_to_declare5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posticpc',
            name='supposed_year_to_declare6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posticpc',
            name='supposed_year_to_declare7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posticpc',
            name='supposed_year_to_declare8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posticpc',
            name='supposed_year_to_declare9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posticpc',
            name='year_FAPPT',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posticpc',
            name='year_OR',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posticpc',
            name='year_ob',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posticpc',
            name='year_of_1st_declaration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posticpc',
            name='year_of_2nd_declaration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posticpc',
            name='year_of_3rd_declaration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posticpc',
            name='year_of_4th_declaration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posticpc',
            name='year_of_5th_declaration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posticpc',
            name='year_of_6th_declaration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posticpc',
            name='year_of_7th_declaration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posticpc',
            name='year_of_8th_declaration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posticpc',
            name='year_of_9th_declaration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postefcc',
            name='Num_Of_YIS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postefcc',
            name='Num_Of_YPIS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postefcc',
            name='add_img_1',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='postefcc',
            name='add_img_10',
            field=models.ImageField(blank=True, default='', null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='postefcc',
            name='add_img_11',
            field=models.ImageField(blank=True, default='', null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='postefcc',
            name='add_img_12',
            field=models.ImageField(blank=True, default='', null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='postefcc',
            name='add_img_13',
            field=models.ImageField(blank=True, default='', null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='postefcc',
            name='add_img_14',
            field=models.ImageField(blank=True, default='', null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='postefcc',
            name='add_img_15',
            field=models.ImageField(blank=True, default='', null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='postefcc',
            name='add_img_16',
            field=models.ImageField(blank=True, default='', null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='postefcc',
            name='add_img_17',
            field=models.ImageField(blank=True, default='', null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='postefcc',
            name='add_img_18',
            field=models.ImageField(blank=True, default='', null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='postefcc',
            name='add_img_19',
            field=models.ImageField(blank=True, default='', null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='postefcc',
            name='add_img_2',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='postefcc',
            name='add_img_20',
            field=models.ImageField(blank=True, default='', null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='postefcc',
            name='add_img_3',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='postefcc',
            name='add_img_4',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='postefcc',
            name='add_img_5',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='postefcc',
            name='add_img_6',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='postefcc',
            name='add_img_7',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='postefcc',
            name='add_img_8',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='postefcc',
            name='add_img_9',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='posticpc',
            name='Num_Of_YIS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posticpc',
            name='Num_Of_YPIS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posticpc',
            name='add_img_1',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='posticpc',
            name='add_img_10',
            field=models.ImageField(blank=True, default='', null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='posticpc',
            name='add_img_11',
            field=models.ImageField(blank=True, default='', null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='posticpc',
            name='add_img_12',
            field=models.ImageField(blank=True, default='', null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='posticpc',
            name='add_img_13',
            field=models.ImageField(blank=True, default='', null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='posticpc',
            name='add_img_14',
            field=models.ImageField(blank=True, default='', null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='posticpc',
            name='add_img_15',
            field=models.ImageField(blank=True, default='', null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='posticpc',
            name='add_img_16',
            field=models.ImageField(blank=True, default='', null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='posticpc',
            name='add_img_17',
            field=models.ImageField(blank=True, default='', null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='posticpc',
            name='add_img_18',
            field=models.ImageField(blank=True, default='', null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='posticpc',
            name='add_img_19',
            field=models.ImageField(blank=True, default='', null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='posticpc',
            name='add_img_2',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='posticpc',
            name='add_img_20',
            field=models.ImageField(blank=True, default='', null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='posticpc',
            name='add_img_3',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='posticpc',
            name='add_img_4',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='posticpc',
            name='add_img_5',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='posticpc',
            name='add_img_6',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='posticpc',
            name='add_img_7',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='posticpc',
            name='add_img_8',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='posticpc',
            name='add_img_9',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
