from django.urls import path
from django.contrib import admin
from . import views
from search.views import SearchView
from Assets.views import (
    PostListWelcomeView,
    PostAntiCorruptView,
    SearchCCBView,
    SearchCCBRegView,
    PostCCBView,
    PostCCBCreateView,
    PostCCBDetailView,
    PostCCBCreateRegisterView,
    PostCCBRegView,
    SearchEFCCView,
    SearchEFCCRegView,
    PostEFCCView,
    PostEFCCCreateView,
    PostEFCCDetailView,
    PostEFCCCreateRegisterView,
    PostEFCCRegView,
    SearchICPCView,
    SearchICPCRegView,
    PostICPCView,
    PostICPCCreateView,
    PostICPCDetailView,
    PostICPCCreateRegisterView,
    PostICPCRegView,
    PostPresidentView,
    PostMinistriesView,
    PostPoliticalView,
    PostUncategorizedView,
    PostDepView,

)

urlpatterns = [
    path('', PostListWelcomeView.as_view(), name='Assets-welcome'),
    path('upload', views.upload, name='upload'),
    path('anti', PostAntiCorruptView.as_view(), name='anti'),
    path('search', SearchView.as_view(), name='search'),
    path('searchccb/', SearchCCBView.as_view(), name='searchccb'),
    path('searchccbreg/', SearchCCBRegView.as_view(), name='searchccbreg'),
    path('displayccb/', PostCCBView.as_view(), name='displayccb'),
    path('ccbPost/new/', PostCCBCreateView.as_view(), name='postccb-create'),
    path('ccb/<int:pk>/', PostCCBDetailView.as_view(), name='ccbpost-detail'),
    path('ccbPostreg/new/', PostCCBCreateRegisterView.as_view(), name='ccbpostreg-detail'),
    path('displayccbreg/', PostCCBRegView.as_view(), name='displayccbreg'),
    path('searchefcc/', SearchEFCCView.as_view(), name='searchefcc'),
    path('searchefccreg/', SearchEFCCRegView.as_view(), name='searchefccreg'),
    path('displayefcc/', PostEFCCView.as_view(), name='displayefcc'),
    path('efccPost/new/', PostEFCCCreateView.as_view(), name='postefcc-create'),
    path('efcc/<int:pk>/', PostEFCCDetailView.as_view(), name='efccpost-detail'),
    path('efccPostreg/new/', PostEFCCCreateRegisterView.as_view(), name='efccpostreg-detail'),
    path('displayefccreg/', PostEFCCRegView.as_view(), name='displayefccreg'),
    path('searchicpc/', SearchICPCView.as_view(), name='searchicpc'),
    path('searchicpcreg/', SearchICPCRegView.as_view(), name='searchicpcreg'),
    path('displayicpc/', PostICPCView.as_view(), name='displayicpc'),
    path('icpcPost/new/', PostICPCCreateView.as_view(), name='posticpc-create'),
    path('icpc/<int:pk>/', PostICPCDetailView.as_view(), name='icpcpost-detail'),
    path('icpcPostreg/new/', PostICPCCreateRegisterView.as_view(), name='icpcpostreg-detail'),
    path('displayicpcreg/', PostICPCRegView.as_view(), name='displayicpcreg'),
    path('pres', PostPresidentView.as_view(), name='pres'),
    path('min', PostMinistriesView.as_view(), name='min'),
    path('pol', PostPoliticalView.as_view(), name='pol'),
    path('uncat', PostUncategorizedView.as_view(), name='uncat'),
    path('dep', PostDepView.as_view(), name='dep'),
]